
tasks:
  - name: Maven Install
    init: mvn clean install -DskipTests=false site:site

github:
  prebuilds:
    master: true
    branches: true

vscode:
  extensions:
    - vscjava.vscode-maven
    - vscjava.vscode-java-pack
