
tasks:
  - name: Maven Install
    init: mvn clean install -DskipTests=false site:site

github:
  prebuilds:
    master: false
    branches: false

vscode:
  extensions:
    - vscjava.vscode-maven
    - vscjava.vscode-java-pack
    - DotJoshJohnson.xml
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
