name: Generate and Publish Site

on:
  push:
    branches: [5-fix-maven-build-to-deplo-maven-site]
  pull_request:
    branches: [main-deact]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "github", "password": "${env.GH_PAGES_PASS}" }]'
      - name: Build Site with Maven
        run: mvn --batch-mode -Preporting site site:stage
      - name: Publish Site with Maven
        run: mvn --batch-mode scm-publish:publish-scm
        env:
           GH_PAGES_PASS: ${{ secrets.GH_PAGES_PASS }}

