name: Generate and Publish Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]    
  workflow_dispatch:
    
permissions:
   contents: read
   pages: write
   id-token: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
      - name: Build and Push Site with Maven
        run: |
           mvn --batch-mode verify site site:stage
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
           path: target/staging

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
