name: Generate and Publish Site

on:
  push:
    branches: [5-fix-maven-build-to-deplo-maven-site]
  pull_request:
    branches: [main-deact]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
      - name: Build and Push Site with Maven
        run: |
           echo "$GITHUB_AUTH_TOKEN" | wc
           mvn --batch-mode site
        env:
           GITHUB_OAUTH_TOKEN: ${{ secrets.GH_PAGES_PASS }}

