name: Publish Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Site with Maven
        run: mvn --batch-mode -Preporting site site:stage
      - name: Publish Site  
        run: mvn --batch-mode scm-publish:publish-scm
